"""add opened_at

Revision ID: 15edf3bc0b37
Revises: 25a4222c3d52
Create Date: 2026-06-09 03:46:01.633278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15edf3bc0b37'
down_revision: Union[str, Sequence[str], None] = '25a4222c3d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_send_logs', sa.Column('opened_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_send_logs', 'opened_at')
    # ### end Alembic commands ###
