"""add clicked_at

Revision ID: 18d1277eccee
Revises: 17f6ce8499d1
Create Date: 2026-06-09 20:08:07.027953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d1277eccee'
down_revision: Union[str, Sequence[str], None] = '17f6ce8499d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_send_logs', sa.Column('clicked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_send_logs', 'clicked_at')
    # ### end Alembic commands ###
