"""add contact subscription status

Revision ID: 615a6ee9ef56
Revises: a47c9203187b
Create Date: 2026-06-10 01:21:28.246619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615a6ee9ef56'
down_revision: Union[str, Sequence[str], None] = 'a47c9203187b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_subscribed')
    # ### end Alembic commands ###
