"""add send_at to campaigns

Revision ID: bb4ce2b99644
Revises: 3bfc33959c75
Create Date: 2026-06-08 20:42:05.997346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4ce2b99644'
down_revision: Union[str, Sequence[str], None] = '3bfc33959c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('send_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'send_at')
    # ### end Alembic commands ###
