"""add contact subscription status

Revision ID: bb5113d50355
Revises: c294be88f094
Create Date: 2026-06-10 01:24:42.932506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5113d50355'
down_revision: Union[str, Sequence[str], None] = 'c294be88f094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('unsubscribe_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contacts', ['unsubscribe_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'unsubscribe_token')
    # ### end Alembic commands ###
