"""add contact subscription status

Revision ID: c294be88f094
Revises: 615a6ee9ef56
Create Date: 2026-06-10 01:23:26.423706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c294be88f094'
down_revision: Union[str, Sequence[str], None] = '615a6ee9ef56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_subscribed')
    op.add_column('contacts', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'is_subscribed')
    op.add_column('campaigns', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
