"""add resend webhook fields

Revision ID: d3124a1ba0cd
Revises: bb5113d50355
Create Date: 2026-06-24 04:21:03.028213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3124a1ba0cd'
down_revision: Union[str, Sequence[str], None] = 'bb5113d50355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_send_logs', sa.Column('provider_message_id', sa.String(), nullable=True))
    op.add_column('campaign_send_logs', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_send_logs', sa.Column('bounced_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_send_logs', sa.Column('bounce_reason', sa.String(), nullable=True))
    op.alter_column('contacts', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('contacts', 'unsubscribe_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'unsubscribe_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('campaign_send_logs', 'bounce_reason')
    op.drop_column('campaign_send_logs', 'bounced_at')
    op.drop_column('campaign_send_logs', 'delivered_at')
    op.drop_column('campaign_send_logs', 'provider_message_id')
    # ### end Alembic commands ###
